### ISSUE TITLE
Part of the screen cropped

### ISSUE THREAD

**Issue by AaronDoesYT** [ShadowTheHedgehogHacking/Widescreen-ShadowTH#2]
For some reason when I've put this patch on and replaced the CSD files, the side of the screen is cutting off I have no idea why

**Comment by dreamsyntax** [comment]
This usually happens if the gecko codes are not on.
Can you add a screenshot to be 100% sure we are looking at the same thing?

It will look like this if CSDFiles replacement is done correctly but the Gecko codes are not applied:
![image](https://user-images.githubusercontent.com/14857235/191322399-0d1e00ca-70f1-4d03-89a1-a730a9ef760d.png)

**Comment by AaronDoesYT** [comment]
If the CSD Patches are on or off, or if the Gecko Codes are on or off I'm getting this regardless atm, also if I put the Advanced Widescreen all in one code on it seems to be cancelling out any of codes I'm using
![image](https://user-images.githubusercontent.com/113984338/191370284-abf979e4-8072-484e-a1dc-2d8521f50952.png)

**Comment by dreamsyntax** [comment]
Is this the USA (GUPE8P) version? This is only compatible with that version.

```
$Advanced Full Widescreen v4 with UI/GNCP Code [dreamsyntax, Dolphin Wiki]
045F67A0 C1700000
045F67A8 44250000
045F67E0 442F0000
045F67D0 C2600000
045F67F0 C2780000
04343228 4E800020
044AB5CC 42F00000
C20BC8D8 00000008
C3629918 81E10094
3E00800B 6210C4B0
7C0F8000 40820028
3DE08057 61EF5F1C
81EF0000 2C0F0002
3DE0804A 61EFB5CC
C36F0000 41820008
FF60D850 00000000
C20622A8 00000006
3DC08057 3DE03F40
91EEE098 3DE0BF40
91EEE084 4E800421
3DE03F80 91EEE098
3DE0BF80 91EEE084
60000000 00000000
C2062300 00000006
3DC08057 3DE03F40
91EEE098 3DE0BF40
91EEE084 4E800421
3DE03F80 91EEE098
3DE0BF80 91EEE084
60000000 00000000
C249475C 00000003
3DC03F40 91C22000
C2222000 EC110032
D0030004 00000000
C2484334 00000002
3DC04000 91C22000
C0822000 00000000
C2036764 00000006
3DC08057 3DE03F40
91EEE098 3DE0BF40
91EEE084 4E800421
3DE03F80 91EEE098
3DE0BF80 91EEE084
60000000 00000000
C236328C 00000006
3DC08057 3DE03F40
91EEE098 3DE0BF40
91EEE084 4E800421
3DE03F80 91EEE098
3DE0BF80 91EEE084
60000000 00000000
C2363180 00000006
3DC08057 3DE03F40
91EEE098 3DE0BF40
91EEE084 4E800421
3DE03F80 91EEE098
3DE0BF80 91EEE084
60000000 00000000
C20BCA54 00000006
3DC08057 3DE03F40
91EEE098 3DE0BF40
91EEE084 4E800421
3DE03F80 91EEE098
3DE0BF80 91EEE084
60000000 00000000
C2345D98 00000006
3DC08057 3DE03F40
91EEE098 3DE0BF40
91EEE084 4E800421
3DE03F80 91EEE098
3DE0BF80 91EEE084
60000000 00000000
*Disable Simple Widescreen by LimblessVector if you use this.
*Do not use with Dolphin Widescreen Hack
*Requires .gncp patches from:
*https://github.com/ShadowTheHedgehogHacking/Widescreen-ShadowTH
*All inclusive code for Single Player only!
```

Try just this code (with the gncp patches) - no other gecko codes enabled.
It is possible you are hitting the gecko limit.

Can you also show me an in-game (not loading screen) screenshot?


And just to be sure

Dolphin -> Config -> Enable Cheats [ ] is on right?


Last possibility: certain old versions of dolphin have issues with some gecko codes.
What version of dolphin are you using?

**Comment by AaronDoesYT** [comment]
I do have a lot of gecko codes on that could be it, I dowloaded a US Rom despite living in PAL region but am using Japanese voice import on that correctly translates the cutscenes into English as playing with English voices and dialogue is like torture to me especially in this game. Don't think that should effect it too much but could do.

In game screenshot
![image](https://user-images.githubusercontent.com/113984338/191375031-b0b2f0a9-6bda-4353-a8f4-eb562f027015.png)

**Comment by dreamsyntax** [comment]
The modifications you mentioned (voice import etc) shouldn't break anything else. 
Unless the voice change was a DOL edit as well (if its just PRS_VOICE_E.afs replacement its fine)

The gecko limit breaking is a possibility, one you can confirm by turning the others off or turning on Dolphin Logs. View -> Log Configuration -> Action Replay (ActionReplay). Set Log to "Info".  Then check Log window for how much gecko space is used.

I am planning to look at optimizing the current gecko code to take less gecko space, it may help with using more cheats.


Edit: Looking at the screenshot, CSDFiles are applied but the gecko definitely is not. So yeah... the above may be the case.

**Comment by AaronDoesYT** [comment]
Still not working after turning off all gecko codes bar the widescreen one, these are the files affected by the other mod btw:  
https://gamebanana.com/mods/download/389670#FileInfo_831279

**Comment by dreamsyntax** [comment]
> Still not working after turning off all gecko codes bar the widescreen one, these are the files affected by the other mod btw: https://gamebanana.com/mods/download/389670#FileInfo_831279

Yeah that mod is fine, has nothing that would break this. Is the gameid GUPE8P and what version of Dolphin are you using?

**Comment by AaronDoesYT** [comment]
It's Dolphin 5.0-17269 and yes the GameID is GUPE8P

**Comment by dreamsyntax** [comment]
> It's Dolphin 5.0-17269 and yes the GameID is GUPE8P

Out of idea then. Check the dolphin logging as stated earlier. Unfortunately I don't know what else the issue could be. It works fine on 3 different devices, OS/arch. Had others try it too. It's also embedded as part of Reloaded project. May be worth seeing if using Reloaded's GUPE8P.ini works or not for you.

**Comment by dreamsyntax** [comment]
I just released v5 beta version of the code, its in the README. It's much smaller, give that a try.

**Comment by AaronDoesYT** [comment]
That's much better now thank you
![image](https://user-images.githubusercontent.com/113984338/191693497-10650515-2135-4fdb-8148-922333d5d5a0.png)

**Comment by dreamsyntax** [comment]
> That's much better now thank you ![image](https://user-images.githubusercontent.com/113984338/191693497-10650515-2135-4fdb-8148-922333d5d5a0.png)

That looks like it should now. I guess the issue was Gecko codespace. Maybe your dolphin ini got messed up somehow and was enabling codes and running out of space.

Either way, closing this since its working properly for you now 👍
